Alterations to improve contrast
quarto-dev/quarto-cli pull request #5953
Opened 2023-06-16 20:14 UTC by rich-iannone

This PR focuses on a few changes that should improve contrast of certain text elements (both in the Cosmo theme and also outside of Bootstrap themes). The original issue https://github.com/quarto-dev/quarto-cli/issues/5780 provides a screenshot of the contrast issues and that is included here as a means for comparison:

<img width="1026" alt="issue-5780" src="https://github.com/quarto-dev/quarto-cli/assets/5612024/8c12b13a-b1b2-4328-9a8a-b7544128b11a">

The purple text color when set against its background gray doesn't provide enough contrast. The same goes for the blue link color. It's not that the background is too dark, rather the text is too light. The right-hand nav text suffers similar problems (even though there is no text background applied). This low contrast is due to two things: small font size, narrow font size, and, on some displays, less ink due to text antialiasing being activated.

We can correct all of these by slightly darkening the text color. For the nav text, it's recommended to have the default font weight of 400 (instead of 300). Decreasing size and weight has a large effect on contrast.

With these changes, we obtain APCA (https://www.myndex.com/APCA/) contrasts between 70 and 80, which is very good. And the color darkening for this PR isn't such that colors lose their identities (they're only slight adjustments that put them in a better place according to the APCA tool).

Here is the rendered document with the CSS changes (I used the same .qmd as the reporter in the referenced issue):

<img width="1155" alt="issue-5780-changed" src="https://github.com/quarto-dev/quarto-cli/assets/5612024/4853ef21-aa6d-4b77-8c34-6fb2cc379a8a">

Fixes: https://github.com/quarto-dev/quarto-cli/issues/5780

2023-06-19 12:53 UTC, dragonstyle commented
If possible, I think it would be very desirable to make this fix without modifying the cosmo bootswatch theme itself - it is ideal we can just automatically update those anytime without needing to manage patches. Additionally, I do worry that there may be other unintended side effects from changing `$blue` since that is a base color.

Now that I'm looking it may just be inadvertent change to cosmo that isn't even necessary... Can you take a quick look when you have time?

2023-06-19 12:53 UTC, dragonstyle requested changes
See note

2023-06-19 14:35 UTC, rich-iannone commented
Will revisit this for sure. Indeed the proposed changes do have far-reaching effects and so we’d want to be careful in getting to the final solution.

2023-06-20 15:12 UTC, dragonstyle approved these changes

2023-06-20 15:12 UTC, merged